In [2]:
!pip install chromadb

Collecting chromadb
  Downloading chromadb-1.5.9-cp39-abi3-win_amd64.whl.metadata (5.1 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.5.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: pydantic>=2.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (2.12.4)
Requirement already satisfied: pydantic-settings>=2.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (2.12.0)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp313-cp313-win_amd64.whl.metadata (9.1 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.49.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: numpy>=1.22.5 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (2.3.5)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.27.0-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.43.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.43.0-py3-none-any.whl.metadata (2.6 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.43.0-py3-none-any.whl.metadata (1.7 kB)
Collecting tokenizers>=0.13.2 (from chromadb)
  Downloading tokenizers-0.23.1-cp310-abi3-win_amd64.whl.metadata (10 kB)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (4.67.1)
Requirement already satisfied: overrides>=7.3.1 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (7.7.0)
Collecting importlib-resources (from chromadb)
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Collecting grpcio>=1.58.0 (from chromadb)
  Downloading grpcio-1.81.1-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (0.20.0)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-36.0.2-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: tenacity>=8.2.3 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (9.1.2)
Requirement already satisfied: pyyaml>=6.0.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (6.0.3)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.2.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Collecting orjson>=3.9.12 (from chromadb)
  Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: httpx>=0.27.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (14.2.0)
Requirement already satisfied: jsonschema>=4.19.0 in c:\users\acer\anaconda3\lib\site-packages (from chromadb) (4.25.0)
Requirement already satisfied: packaging>=24.0 in c:\users\acer\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (25.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: colorama in c:\users\acer\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: anyio in c:\users\acer\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (4.10.0)
Requirement already satisfied: certifi in c:\users\acer\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\acer\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in c:\users\acer\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\acer\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\acer\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\acer\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\acer\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\acer\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.28.0)
Requirement already satisfied: six>=1.9.0 in c:\users\acer\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\acer\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\acer\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.32.5)
Collecting requests-oauthlib (from kubernetes>=28.1.0->chromadb)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in c:\users\acer\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Collecting aiohttp<4.0.0,>=3.13.5 (from kubernetes>=28.1.0->chromadb)
  Downloading aiohttp-3.14.1-cp313-cp313-win_amd64.whl.metadata (8.5 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\acer\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\acer\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\acer\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\acer\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\acer\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\acer\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.22.0)
Collecting flatbuffers (from onnxruntime>=1.14.1->chromadb)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: protobuf>=4.25.8 in c:\users\acer\anaconda3\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (5.29.3)
Collecting googleapis-common-protos~=1.57 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Collecting opentelemetry-exporter-otlp-proto-common==1.43.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.43.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.43.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.43.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-semantic-conventions==0.64b0 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.64b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\acer\anaconda3\lib\site-packages (from pydantic>=2.0->chromadb) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\acer\anaconda3\lib\site-packages (from pydantic>=2.0->chromadb) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\acer\anaconda3\lib\site-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\acer\anaconda3\lib\site-packages (from pydantic-settings>=2.0->chromadb) (1.1.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\acer\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\acer\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\acer\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Collecting huggingface-hub<2.0,>=0.16.4 (from tokenizers>=0.13.2->chromadb)
  Downloading huggingface_hub-1.21.0-py3-none-any.whl.metadata (14 kB)
Collecting click>=8.4.0 (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\acer\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\acer\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.10.0)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb)
  Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\acer\anaconda3\lib\site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.8.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.8.0-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Collecting watchfiles>=0.20 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-1.2.0-cp313-cp313-win_amd64.whl.metadata (5.0 kB)
Collecting websockets>=10.4 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading websockets-16.0-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: sniffio>=1.1 in c:\users\acer\anaconda3\lib\site-packages (from anyio->httpx>=0.27.0->chromadb) (1.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\acer\anaconda3\lib\site-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.4)
Collecting oauthlib>=3.0.0 (from requests-oauthlib->kubernetes>=28.1.0->chromadb)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Downloading chromadb-1.5.9-cp39-abi3-win_amd64.whl (23.5 MB)
   ---------------------------------------- 0.0/23.5 MB ? eta -:--:--
   -- ------------------------------------- 1.3/23.5 MB 6.9 MB/s eta 0:00:04
   ---- ----------------------------------- 2.9/23.5 MB 7.2 MB/s eta 0:00:03
   ------- -------------------------------- 4.5/23.5 MB 7.5 MB/s eta 0:00:03
   ---------- ----------------------------- 6.0/23.5 MB 7.3 MB/s eta 0:00:03
   ------------ --------------------------- 7.6/23.5 MB 7.3 MB/s eta 0:00:03
   --------------- ------------------------ 8.9/23.5 MB 7.1 MB/s eta 0:00:03
   ----------------- ---------------------- 10.5/23.5 MB 7.2 MB/s eta 0:00:02
   ------------------- -------------------- 11.5/23.5 MB 7.1 MB/s eta 0:00:02
   ---------------------- ----------------- 13.4/23.5 MB 7.1 MB/s eta 0:00:02
   ------------------------- -------------- 14.9/23.5 MB 7.2 MB/s eta 0:00:02
   ---------------------------- ----------- 16.8/23.5 MB 7.3 MB/s eta 0:00:01
   ------------------------------- -------- 18.4/23.5 MB 7.4 MB/s eta 0:00:01
   ---------------------------------- ----- 20.2/23.5 MB 7.5 MB/s eta 0:00:01
   ------------------------------------ --- 21.5/23.5 MB 7.4 MB/s eta 0:00:01
   ------------------------------------- -- 22.3/23.5 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 23.5/23.5 MB 7.1 MB/s  0:00:03
Downloading build-1.5.0-py3-none-any.whl (26 kB)
Downloading grpcio-1.81.1-cp313-cp313-win_amd64.whl (4.9 MB)
   ---------------------------------------- 0.0/4.9 MB ? eta -:--:--
   ---------- ----------------------------- 1.3/4.9 MB 6.4 MB/s eta 0:00:01
   ----------------------- ---------------- 2.9/4.9 MB 7.1 MB/s eta 0:00:01
   ------------------------------------ --- 4.5/4.9 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 4.9/4.9 MB 7.1 MB/s  0:00:00
Downloading kubernetes-36.0.2-py2.py3-none-any.whl (4.6 MB)
   ---------------------------------------- 0.0/4.6 MB ? eta -:--:--
   ------------- -------------------------- 1.6/4.6 MB 7.8 MB/s eta 0:00:01
   ------------------------ --------------- 2.9/4.6 MB 7.0 MB/s eta 0:00:01
   ----------------------------- ---------- 3.4/4.6 MB 5.8 MB/s eta 0:00:01
   -------------------------------------- - 4.5/4.6 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 4.6/4.6 MB 5.2 MB/s  0:00:00
Downloading aiohttp-3.14.1-cp313-cp313-win_amd64.whl (479 kB)
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading mmh3-5.2.1-cp313-cp313-win_amd64.whl (41 kB)
Downloading onnxruntime-1.27.0-cp313-cp313-win_amd64.whl (13.4 MB)
   ---------------------------------------- 0.0/13.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/13.4 MB 4.7 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/13.4 MB 6.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.9/13.4 MB 6.6 MB/s eta 0:00:02
   ---------------- ----------------------- 5.5/13.4 MB 6.7 MB/s eta 0:00:02
   ------------------- -------------------- 6.6/13.4 MB 6.7 MB/s eta 0:00:02
   ------------------------ --------------- 8.1/13.4 MB 6.5 MB/s eta 0:00:01
   --------------------------- ------------ 9.2/13.4 MB 6.5 MB/s eta 0:00:01
   ------------------------------- -------- 10.5/13.4 MB 6.4 MB/s eta 0:00:01
   ----------------------------------- ---- 11.8/13.4 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------  13.1/13.4 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 13.4/13.4 MB 6.3 MB/s  0:00:02
Downloading opentelemetry_api-1.43.0-py3-none-any.whl (61 kB)
Downloading opentelemetry_exporter_otlp_proto_grpc-1.43.0-py3-none-any.whl (19 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.43.0-py3-none-any.whl (17 kB)
Downloading opentelemetry_proto-1.43.0-py3-none-any.whl (72 kB)
Downloading googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)
Downloading opentelemetry_sdk-1.43.0-py3-none-any.whl (178 kB)
Downloading opentelemetry_semantic_conventions-0.64b0-py3-none-any.whl (203 kB)
Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl (127 kB)
Downloading pybase64-1.4.3-cp313-cp313-win_amd64.whl (35 kB)
Downloading pypika-0.51.1-py2.py3-none-any.whl (60 kB)
Downloading tokenizers-0.23.1-cp310-abi3-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   -------------- ------------------------- 1.0/2.8 MB 6.8 MB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 6.4 MB/s  0:00:00
Downloading huggingface_hub-1.21.0-py3-none-any.whl (721 kB)
   ---------------------------------------- 0.0/721.1 kB ? eta -:--:--
   ---------------------------------------- 721.1/721.1 kB 3.8 MB/s  0:00:00
Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------- -------------------------- 1.3/4.0 MB 6.5 MB/s eta 0:00:01
   ----------------------- ---------------- 2.4/4.0 MB 6.0 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 5.8 MB/s  0:00:00
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading uvicorn-0.49.0-py3-none-any.whl (71 kB)
Downloading httptools-0.8.0-cp313-cp313-win_amd64.whl (90 kB)
Downloading watchfiles-1.2.0-cp313-cp313-win_amd64.whl (288 kB)
Downloading websockets-16.0-cp313-cp313-win_amd64.whl (178 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading importlib_resources-7.1.0-py3-none-any.whl (37 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
Installing collected packages: pypika, flatbuffers, durationpy, websockets, pyproject_hooks, pybase64, orjson, opentelemetry-proto, opentelemetry-api, onnxruntime, oauthlib, mmh3, importlib-resources, httptools, hf-xet, grpcio, googleapis-common-protos, click, watchfiles, uvicorn, requests-oauthlib, opentelemetry-semantic-conventions, opentelemetry-exporter-otlp-proto-common, build, aiohttp, opentelemetry-sdk, kubernetes, opentelemetry-exporter-otlp-proto-grpc, huggingface-hub, tokenizers, chromadb

   - --------------------------------------  1/31 [flatbuffers]
   --- ------------------------------------  3/31 [websockets]
   ------ ---------------------------------  5/31 [pybase64]
   ---------- -----------------------------  8/31 [opentelemetry-api]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ----------- ----------------------------  9/31 [onnxruntime]
   ------------ --------------------------- 10/31 [oauthlib]
   ------------ --------------------------- 10/31 [oauthlib]
   ------------ --------------------------- 10/31 [oauthlib]
   --------------- ------------------------ 12/31 [importlib-resources]
   ---------------- ----------------------- 13/31 [httptools]
   ------------------- -------------------- 15/31 [grpcio]
   ------------------- -------------------- 15/31 [grpcio]
   ------------------- -------------------- 15/31 [grpcio]
   ------------------- -------------------- 15/31 [grpcio]
   -------------------- ------------------- 16/31 [googleapis-common-protos]
   -------------------- ------------------- 16/31 [googleapis-common-protos]
  Attempting uninstall: click
   -------------------- ------------------- 16/31 [googleapis-common-protos]
    Found existing installation: click 8.2.1
   -------------------- ------------------- 16/31 [googleapis-common-protos]
    Uninstalling click-8.2.1:
   -------------------- ------------------- 16/31 [googleapis-common-protos]
      Successfully uninstalled click-8.2.1
   -------------------- ------------------- 16/31 [googleapis-common-protos]
   --------------------- ------------------ 17/31 [click]
   --------------------- ------------------ 17/31 [click]
   ------------------------ --------------- 19/31 [uvicorn]
   ------------------------ --------------- 19/31 [uvicorn]
   ---------------------- ---------- 21/31 [opentelemetry-semantic-conventions]

In [4]:
import chromadb as cdb
import pandas as pd

In [7]:
df = pd.read_csv('medium_posts_kaggle_style_7500.csv')
df.head()

,title,subtitle,subtitle_truncated_flag,category,author,author_id,published_date,reading_time_minutes,word_count,claps,voters,responses,url,tags
0,Ultimate Guide to Sql #1,"Learn sql with real-world examples, best pract...",False,sql,Alice Johnson,1380,2023-07-18,10,1514,9144,839,346,https://medium.com/@demo/post-1,career;databricks;machine-learning
1,Hands-on Guide to Snowflake #2,"Learn snowflake with real-world examples, best...",False,snowflake,Alice Johnson,1016,2022-07-11,9,1552,33118,4931,13,https://medium.com/@demo/post-2,databricks;programming;career
2,Complete Guide to Cloud Computing #3,Learn cloud computing with real-world examples...,False,cloud-computing,Michael Chen,1302,2023-07-24,3,1253,45753,3462,174,https://medium.com/@demo/post-3,software-engineering;data-science;programming
3,Ultimate Guide to Python #4,"Learn python with real-world examples, best pr...",False,python,Bob Smith,1195,2022-07-18,14,2008,39565,2166,413,https://medium.com/@demo/post-4,artificial-intelligence;big-data;databricks
4,Hands-on Guide to Machine Learning #5,Learn machine learning with real-world example...,False,machine-learning,Bob Smith,1283,2023-08-24,14,2964,12601,569,23,https://medium.com/@demo/post-5,sql;programming;software-engineering

In [8]:
df = df.dropna()

df = df[~df['subtitle_truncated_flag']]

In [12]:
topic_of_learning = ["python", "cloud-computing", "data-science"]
df = df[df['category'].isin(topic_of_learning)]
df['text'] = df['title'] + " " + df['subtitle']
df['meta'] = df.apply(lambda x: {"text": x['text'], "category": x['category']}, axis=1)

C:\Users\acer\AppData\Local\Temp\ipykernel_18228\1402106662.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['title'] + " " + df['subtitle']
C:\Users\acer\AppData\Local\Temp\ipykernel_18228\1402106662.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['meta'] = df.apply(lambda x: {"text": x['text'], "category": x['category']}, axis=1)

In [14]:
df.head()

,title,subtitle,subtitle_truncated_flag,category,author,author_id,published_date,reading_time_minutes,word_count,claps,voters,responses,url,tags,text,meta
2,Complete Guide to Cloud Computing #3,Learn cloud computing with real-world examples...,False,cloud-computing,Michael Chen,1302,2023-07-24,3,1253,45753,3462,174,https://medium.com/@demo/post-3,software-engineering;data-science;programming,Complete Guide to Cloud Computing #3 Learn clo...,{'text': 'Complete Guide to Cloud Computing #3...
3,Ultimate Guide to Python #4,"Learn python with real-world examples, best pr...",False,python,Bob Smith,1195,2022-07-18,14,2008,39565,2166,413,https://medium.com/@demo/post-4,artificial-intelligence;big-data;databricks,Ultimate Guide to Python #4 Learn python with ...,{'text': 'Ultimate Guide to Python #4 Learn py...
15,Advanced Guide to Data Science #16,"Learn data science with real-world examples, b...",False,data-science,Michael Chen,1485,2025-01-30,8,1685,34581,4969,216,https://medium.com/@demo/post-16,programming;databricks;career,Advanced Guide to Data Science #16 Learn data ...,{'text': 'Advanced Guide to Data Science #16 L...
19,Complete Guide to Cloud Computing #20,Learn cloud computing with real-world examples...,False,cloud-computing,Bob Smith,1050,2024-06-01,14,2334,26941,3825,442,https://medium.com/@demo/post-20,career;artificial-intelligence;machine-learning,Complete Guide to Cloud Computing #20 Learn cl...,{'text': 'Complete Guide to Cloud Computing #2...
30,Practical Guide to Data Science #31,"Learn data science with real-world examples, b...",False,data-science,Emma Wilson,1310,2023-03-08,13,1433,45055,2162,258,https://medium.com/@demo/post-31,big-data;software-engineering;artificial-intel...,Practical Guide to Data Science #31 Learn data...,{'text': 'Practical Guide to Data Science #31 ...

In [15]:
# chroma db setup
client = cdb.Client() # in memry database
# create a collection
collection = client.create_collection(name="medium_posts")

In [ ]:
collection.add(
    ids=[str(x) for x in df['id'].tolist()],
    documents=df['text'].tolist(),
    metadatas=df['meta'].tolist()
)

KeyError: 'id'